### ISSUE TITLE
总结的内容发送Blinko会发送两次

### ISSUE THREAD

**Issue by ywxhqwq** [BryceWG/Blinko-Chrome-Extention#3]
使用总结功能时，点击修改并保存之后，在Blinko中会有两篇一样的文章

![image](https://github.com/user-attachments/assets/9cc3d732-1db0-4e09-9f39-b754bba22439)
![image](https://github.com/user-attachments/assets/70d03860-2f88-4ad0-b73c-8a37320618eb)

插件版本1.6
![image](https://github.com/user-attachments/assets/c19a9622-f4ea-4e99-9155-e0f1306162f0)

**Comment by BryceWG** [comment]
收到,你可以先用悬浮窗进行总结

**Comment by BryceWG** [comment]
新版已修复
