### ISSUE TITLE
你在插件市场上有发布吗? 看到一个不知道是不是你的

### ISSUE THREAD

**Issue by LiangWei88** [BryceWG/Blinko-Chrome-Extention#6]
https://chromewebstore.google.com/detail/Blinko%E7%BD%91%E9%A1%B5%E5%86%85%E5%AE%B9%E6%8F%90%E5%8F%96%E6%80%BB%E7%BB%93/gpdobkhkjbgbgllpkhaomajicoaccjjo?hl=zh-CN&utm_source=ext_sidebar

**Comment by BryceWG** [comment]
有发布,委托别人代发的
